const mongoose = require("mongoose");

/**
 * Technical Question Schema
 */
const technicalQuestionSchema = new mongoose.Schema(
    {
        question: {
            type: String,
            required: [true, "Technical question is required"],
        },

        intention: {
            type: String,
            required: [true, "Intention is required"],
        },

        answer: {
            type: String,
            required: [true, "Answer is required"],
        },
    },
    {
        _id: false,
    }
);


/**
 * Behavioral Question Schema
 */
const behavioralQuestionSchema = new mongoose.Schema(
    {
        question: {
            type: String,
            required: [true, "Behavioral question is required"],
        },

        intention: {
            type: String,
            required: [true, "Intention is required"],
        },

        answer: {
            type: String,
            required: [true, "Answer is required"],
        },
    },
    {
        _id: false,
    }
);


/**
 * Skill Gap Schema
 */
const skillGapSchema = new mongoose.Schema(
    {
        skill: {
            type: String,
            required: [true, "Skill is required"],
        },

        severity: {
            type: String,
            enum: ["low", "medium", "high"],
            required: [true, "Severity is required"],
        },
    },
    {
        _id: false,
    }
);


/**
 * Preparation Plan Schema
 */
const preparationPlanSchema = new mongoose.Schema(
    {
        day: {
            type: Number,
            required: [true, "Day is required"],
        },

        focus: {
            type: String,
            required: [true, "Focus is required"],
        },

        tasks: [
            {
                type: String,
                required: [true, "Task is required"],
            },
        ],
    },
    {
        _id: false,
    }
);


/**
 * Interview Report Schema
 */
const interviewReportSchema = new mongoose.Schema(
    {
        /**
         * Job Description
         */
        jobDescription: {
            type: String,
            required: [true, "Job description is required"],
        },


        /**
         * Extracted resume text
         */
        resume: {
            type: String,
        },


        /**
         * User's self description
         */
        selfDescription: {
            type: String,
        },


        /**
         * AI generated match score
         */
        matchScore: {
            type: Number,
            min: 0,
            max: 100,
        },


        /**
         * Job title generated by AI
         */
        title: {
            type: String,
            required: [true, "Job title is required"],
        },


        /**
         * Technical Interview Questions
         */
        technicalQuestions: {
            type: [technicalQuestionSchema],
            default: [],
        },


        /**
         * Behavioral Interview Questions
         */
        behavioralQuestions: {
            type: [behavioralQuestionSchema],
            default: [],
        },


        /**
         * Skill Gaps
         */
        skillGaps: {
            type: [skillGapSchema],
            default: [],
        },


        /**
         * Preparation Plan
         */
        preparationPlan: {
            type: [preparationPlanSchema],
            default: [],
        },


        /**
         * User who generated this report
         */
        user: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "users",
            required: true,
        },
    },
    {
        timestamps: true,
    }
);


/**
 * Create Interview Report Model
 */
const interviewReportModel = mongoose.model(
    "InterviewReport",
    interviewReportSchema
);


/**
 * Export Model
 */
module.exports = interviewReportModel;